name: AllChecks
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Check changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ./gradlew onChainCheck -PfileToCheck=$file
          done
  
      - name: Build
        run: |
          ./gradlew run
